schema {
  query: RootQueryType
  mutation: RootMutationType
}

input ShapeInput {
  kind: String
  geometry: [[Float]]
}

type RootMutationType {
  createPunchListItem(shapes: [ShapeInput]): String!
}

type RootQueryType {
  hello(name: String!): String!
  characters: [Character!]!
}

interface Character {
  name: String!
}

interface Species implements Character {
  name: String!
  numberOfHearts: Int!
}

type Human implements Character & Species {
  name: String!
  numberOfHearts: Int!
  ogTerrain: Boolean!
}
