-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object exposing (Online_users(..), Online_users_aggregate(..), Online_users_aggregate_fields(..), Online_users_avg_fields(..), Online_users_max_fields(..), Online_users_min_fields(..), Online_users_mutation_response(..), Online_users_stddev_fields(..), Online_users_stddev_pop_fields(..), Online_users_stddev_samp_fields(..), Online_users_sum_fields(..), Online_users_var_pop_fields(..), Online_users_var_samp_fields(..), Online_users_variance_fields(..), Todolist(..), Todolist_aggregate(..), Todolist_aggregate_fields(..), Todolist_avg_fields(..), Todolist_max_fields(..), Todolist_min_fields(..), Todolist_mutation_response(..), Todolist_stddev_fields(..), Todolist_stddev_pop_fields(..), Todolist_stddev_samp_fields(..), Todolist_sum_fields(..), Todolist_var_pop_fields(..), Todolist_var_samp_fields(..), Todolist_variance_fields(..), Users(..), Users_aggregate(..), Users_aggregate_fields(..), Users_avg_fields(..), Users_max_fields(..), Users_min_fields(..), Users_mutation_response(..), Users_stddev_fields(..), Users_stddev_pop_fields(..), Users_stddev_samp_fields(..), Users_sum_fields(..), Users_var_pop_fields(..), Users_var_samp_fields(..), Users_variance_fields(..))


type Online_users
    = Online_users


type Online_users_aggregate
    = Online_users_aggregate


type Online_users_aggregate_fields
    = Online_users_aggregate_fields


type Online_users_avg_fields
    = Online_users_avg_fields


type Online_users_max_fields
    = Online_users_max_fields


type Online_users_min_fields
    = Online_users_min_fields


type Online_users_mutation_response
    = Online_users_mutation_response


type Online_users_stddev_fields
    = Online_users_stddev_fields


type Online_users_stddev_pop_fields
    = Online_users_stddev_pop_fields


type Online_users_stddev_samp_fields
    = Online_users_stddev_samp_fields


type Online_users_sum_fields
    = Online_users_sum_fields


type Online_users_var_pop_fields
    = Online_users_var_pop_fields


type Online_users_var_samp_fields
    = Online_users_var_samp_fields


type Online_users_variance_fields
    = Online_users_variance_fields


type Todolist
    = Todolist


type Todolist_aggregate
    = Todolist_aggregate


type Todolist_aggregate_fields
    = Todolist_aggregate_fields


type Todolist_avg_fields
    = Todolist_avg_fields


type Todolist_max_fields
    = Todolist_max_fields


type Todolist_min_fields
    = Todolist_min_fields


type Todolist_mutation_response
    = Todolist_mutation_response


type Todolist_stddev_fields
    = Todolist_stddev_fields


type Todolist_stddev_pop_fields
    = Todolist_stddev_pop_fields


type Todolist_stddev_samp_fields
    = Todolist_stddev_samp_fields


type Todolist_sum_fields
    = Todolist_sum_fields


type Todolist_var_pop_fields
    = Todolist_var_pop_fields


type Todolist_var_samp_fields
    = Todolist_var_samp_fields


type Todolist_variance_fields
    = Todolist_variance_fields


type Users
    = Users


type Users_aggregate
    = Users_aggregate


type Users_aggregate_fields
    = Users_aggregate_fields


type Users_avg_fields
    = Users_avg_fields


type Users_max_fields
    = Users_max_fields


type Users_min_fields
    = Users_min_fields


type Users_mutation_response
    = Users_mutation_response


type Users_stddev_fields
    = Users_stddev_fields


type Users_stddev_pop_fields
    = Users_stddev_pop_fields


type Users_stddev_samp_fields
    = Users_stddev_samp_fields


type Users_sum_fields
    = Users_sum_fields


type Users_var_pop_fields
    = Users_var_pop_fields


type Users_var_samp_fields
    = Users_var_samp_fields


type Users_variance_fields
    = Users_variance_fields
