-- Do not manually edit this file, it was auto-generated by Graphqelm
-- npm package version 1.0.1
-- Target elm package version 4.1.0
-- https://github.com/dillonkearns/graphqelm


module Github.InputObject exposing (..)


type AcceptTopicSuggestionInput
    = AcceptTopicSuggestionInput


type AddCommentInput
    = AddCommentInput


type AddProjectCardInput
    = AddProjectCardInput


type AddProjectColumnInput
    = AddProjectColumnInput


type AddPullRequestReviewCommentInput
    = AddPullRequestReviewCommentInput


type AddPullRequestReviewInput
    = AddPullRequestReviewInput


type AddReactionInput
    = AddReactionInput


type AddStarInput
    = AddStarInput


type CommitAuthor
    = CommitAuthor


type CreateProjectInput
    = CreateProjectInput


type DeclineTopicSuggestionInput
    = DeclineTopicSuggestionInput


type DeleteProjectCardInput
    = DeleteProjectCardInput


type DeleteProjectColumnInput
    = DeleteProjectColumnInput


type DeleteProjectInput
    = DeleteProjectInput


type DeletePullRequestReviewInput
    = DeletePullRequestReviewInput


type DismissPullRequestReviewInput
    = DismissPullRequestReviewInput


type DraftPullRequestReviewComment
    = DraftPullRequestReviewComment


type GistOrder
    = GistOrder


type IssueOrder
    = IssueOrder


type LanguageOrder
    = LanguageOrder


type MoveProjectCardInput
    = MoveProjectCardInput


type MoveProjectColumnInput
    = MoveProjectColumnInput


type ProjectOrder
    = ProjectOrder


type ReactionOrder
    = ReactionOrder


type RefOrder
    = RefOrder


type ReleaseOrder
    = ReleaseOrder


type RemoveOutsideCollaboratorInput
    = RemoveOutsideCollaboratorInput


type RemoveReactionInput
    = RemoveReactionInput


type RemoveStarInput
    = RemoveStarInput


type RepositoryOrder
    = RepositoryOrder


type RequestReviewsInput
    = RequestReviewsInput


type StarOrder
    = StarOrder


type SubmitPullRequestReviewInput
    = SubmitPullRequestReviewInput


type TeamOrder
    = TeamOrder


type TeamRepositoryOrder
    = TeamRepositoryOrder


type UpdateProjectCardInput
    = UpdateProjectCardInput


type UpdateProjectColumnInput
    = UpdateProjectColumnInput


type UpdateProjectInput
    = UpdateProjectInput


type UpdatePullRequestReviewCommentInput
    = UpdatePullRequestReviewCommentInput


type UpdatePullRequestReviewInput
    = UpdatePullRequestReviewInput


type UpdateSubscriptionInput
    = UpdateSubscriptionInput


type UpdateTopicsInput
    = UpdateTopicsInput
