-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EdgeCases.Object.Human exposing (..)

import EdgeCases.InputObject
import EdgeCases.Interface
import EdgeCases.Object
import EdgeCases.Scalar
import EdgeCases.ScalarCodecs
import EdgeCases.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


name : SelectionSet String EdgeCases.Object.Human
name =
    Object.selectionForField "String" "name" [] Decode.string


numberOfHearts : SelectionSet Int EdgeCases.Object.Human
numberOfHearts =
    Object.selectionForField "Int" "numberOfHearts" [] Decode.int


ogTerrain : SelectionSet Bool EdgeCases.Object.Human
ogTerrain =
    Object.selectionForField "Bool" "ogTerrain" [] Decode.bool
