-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Swapi.Scalar exposing (Decoders, Id(..), PosixTime(..), defaultCodecs, defineCodecs, unwrapCodecs)

import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Json.Decode as Decode exposing (Decoder)


type Id
    = Id String


type PosixTime
    = PosixTime String


defineCodecs :
    { codecId : Codec valueId
    , codecPosixTime : Codec valuePosixTime
    }
    -> Decoders valueId valuePosixTime
defineCodecs definitions =
    Decoders
        { codecId = definitions.codecId
        , codecPosixTime = definitions.codecPosixTime
        }


unwrapCodecs :
    Decoders valueId valuePosixTime
    ->
        { codecId : Codec valueId
        , codecPosixTime : Codec valuePosixTime
        }
unwrapCodecs (Decoders unwrappedDecoders) =
    unwrappedDecoders


type Decoders valueId valuePosixTime
    = Decoders (RawDecoders valueId valuePosixTime)


type alias RawDecoders valueId valuePosixTime =
    { codecId : Codec valueId
    , codecPosixTime : Codec valuePosixTime
    }


type alias Codec elmValue =
    { encoder : elmValue -> Value
    , decoder : Decoder elmValue
    }


defaultCodecs : RawDecoders Id PosixTime
defaultCodecs =
    { codecId = Codec (\(Id rawId) -> Encode.string rawId) (Object.scalarDecoder |> Decode.map Id)
    , codecPosixTime = Codec (\(PosixTime rawId) -> Encode.string rawId) (Object.scalarDecoder |> Decode.map PosixTime)
    }
