-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Enum.PullRequestPubSubTopic exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The possible PubSub channels for a pull request.

  - Updated - The channel ID for observing pull request updates.
  - Markasread - The channel ID for marking an pull request as read.
  - HeadRef - The channel ID for observing head ref updates.

-}
type PullRequestPubSubTopic
    = Updated
    | Markasread
    | HeadRef


list : List PullRequestPubSubTopic
list =
    [ Updated, Markasread, HeadRef ]


decoder : Decoder PullRequestPubSubTopic
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "UPDATED" ->
                        Decode.succeed Updated

                    "MARKASREAD" ->
                        Decode.succeed Markasread

                    "HEAD_REF" ->
                        Decode.succeed HeadRef

                    _ ->
                        Decode.fail ("Invalid PullRequestPubSubTopic type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : PullRequestPubSubTopic -> String
toString enum____ =
    case enum____ of
        Updated ->
            "UPDATED"

        Markasread ->
            "MARKASREAD"

        HeadRef ->
            "HEAD_REF"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PullRequestPubSubTopic
fromString enumString____ =
    case enumString____ of
        "UPDATED" ->
            Just Updated

        "MARKASREAD" ->
            Just Markasread

        "HEAD_REF" ->
            Just HeadRef

        _ ->
            Nothing
