-- Do not manually edit this file, it was auto-generated by Graphqelm
-- npm package version 2.0.2
-- Target elm package version 6.1.0
-- https://github.com/dillonkearns/graphqelm


module Github.Enum.ReleaseOrderField exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Properties by which release connections can be ordered.

  - CreatedAt - Order releases by creation time
  - Name - Order releases alphabetically by name

-}
type ReleaseOrderField
    = CreatedAt
    | Name


decoder : Decoder ReleaseOrderField
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "CREATED_AT" ->
                        Decode.succeed CreatedAt

                    "NAME" ->
                        Decode.succeed Name

                    _ ->
                        Decode.fail ("Invalid ReleaseOrderField type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ReleaseOrderField -> String
toString enum =
    case enum of
        CreatedAt ->
            "CREATED_AT"

        Name ->
            "NAME"
