-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.Todolist_max_fields exposing (created_at, id, task, user_id)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.ScalarCodecs
import Hasura.Union
import Json.Decode as Decode


created_at : SelectionSet (Maybe Hasura.ScalarCodecs.Timestamptz) Hasura.Object.Todolist_max_fields
created_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "created_at" [] (Hasura.ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


id : SelectionSet (Maybe Int) Hasura.Object.Todolist_max_fields
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


task : SelectionSet (Maybe String) Hasura.Object.Todolist_max_fields
task =
    Object.selectionForField "(Maybe String)" "task" [] (Decode.string |> Decode.nullable)


user_id : SelectionSet (Maybe Int) Hasura.Object.Todolist_max_fields
user_id =
    Object.selectionForField "(Maybe Int)" "user_id" [] (Decode.int |> Decode.nullable)
