module Graphqelm.Operation exposing (RootMutation, RootQuery)

{-| This module contains types used to annotate top-level queries which can be
built up using functions in code generated by the `graphqelm` command line tool
and sent using functions in the `Graphqelm.Http` module.

@docs RootMutation, RootQuery

-}


{-| Type for top-level queries which can be sent using functions
from `Graphqelm.Http`.
-}
type RootQuery
    = RootQuery


{-| Type for top-level mutations which can be sent using functions
from `Graphqelm.Http`.
-}
type RootMutation
    = RootMutation
