-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Github.Object.CommitCommentEdge exposing (..)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Github.Object.CommitCommentEdge
selection constructor =
    Object.selection constructor


typename__ : Field String Github.Object.CommitCommentEdge
typename__ =
    Object.fieldDecoder "__typename" [] Decode.string


{-| A cursor for use in pagination.
-}
cursor : Field String Github.Object.CommitCommentEdge
cursor =
    Object.fieldDecoder "cursor" [] Decode.string


{-| The item at the end of the edge.
-}
node : SelectionSet decodesTo Github.Object.CommitComment -> Field (Maybe decodesTo) Github.Object.CommitCommentEdge
node object =
    Object.selectionField "node" [] object (identity >> Decode.nullable)
